// src/components/workshop/TvPromoSlideView.tsx
import React, { useMemo } from 'react';
import { TVAdSlide, isVideoMedia } from '../../utils/tvAdMediaService';
import { Megaphone, Clock } from 'lucide-react';

interface TvPromoSlideViewProps {
  slide: TVAdSlide;
  slideIndex: number;
  totalSlides: number;
  durationSeconds: number;
  secondsRemaining: number;
  progressPercent: number;
  companyLogoUrl?: string;
  companyName?: string;
  nextSlideUrl?: string;
  onSkipToSchedule?: () => void;
}

/**
 * Detects if a text string looks like a raw/auto-generated file name
 * (e.g., "Unnamed (4)", "WhatsApp Image...", "IMG_2026...", "Screenshot...", etc.)
 */
const isAutoGeneratedFileName = (text?: string): boolean => {
  if (!text) return true;
  const clean = text.trim().toLowerCase();
  if (!clean) return true;

  if (
    clean.startsWith('unnamed') ||
    clean.startsWith('whatsapp image') ||
    clean.startsWith('whatsapp') ||
    clean.startsWith('screenshot') ||
    clean.startsWith('img') ||
    clean.startsWith('image') ||
    clean.startsWith('dsc_') ||
    clean.startsWith('photo') ||
    clean.startsWith('download') ||
    clean.startsWith('video_') ||
    clean.startsWith('vid_') ||
    /\.(png|jpg|jpeg|webp|gif|svg|mp4|mov|webm)$/i.test(clean) ||
    /^[0-9a-f_-]{8,}$/i.test(clean)
  ) {
    return true;
  }
  return false;
};

export const TvPromoSlideView: React.FC<TvPromoSlideViewProps> = ({
  slide,
  slideIndex,
  totalSlides,
  durationSeconds,
  secondsRemaining,
  progressPercent,
  companyLogoUrl = '/assets/logos/aie-skyline.png',
  companyName = 'AIE SKYLINE LIMITED',
  nextSlideUrl,
  onSkipToSchedule,
}) => {
  // Preload next slide media in the background so the next transition is instant without flash
  React.useEffect(() => {
    if (!nextSlideUrl) return;
    if (isVideoMedia(nextSlideUrl)) {
      try {
        const v = document.createElement('video');
        v.preload = 'auto';
        v.src = nextSlideUrl;
        v.muted = true;
      } catch {}
    } else {
      try {
        const i = new Image();
        i.src = nextSlideUrl;
      } catch {}
    }
  }, [nextSlideUrl]);

  const isVideo = useMemo(() => {
    return slide.mediaType === 'video' || isVideoMedia(slide.imageUrl);
  }, [slide.mediaType, slide.imageUrl]);

  const fitMode = slide.fit === 'contain' ? 'contain' : 'cover';

  // 1. Hide File Name Overlays:
  // Only display custom title captions IF explicitly entered in the TV Settings modal;
  // otherwise, hide caption overlays completely.
  const hasCustomTitle = useMemo(() => {
    if (slide.hasCustomTitle) return true;
    if (!slide.title) return false;
    return !isAutoGeneratedFileName(slide.title);
  }, [slide.hasCustomTitle, slide.title]);

  const hasCustomSubtitle = useMemo(() => {
    if (!slide.subtitle) return false;
    const clean = slide.subtitle.trim();
    if (!clean) return false;
    // Don't show default placeholder subtitles
    if (
      clean.toLowerCase() === 'promotional banner & fleet services' ||
      clean.toLowerCase() === 'promotional announcement'
    ) {
      return false;
    }
    return !isAutoGeneratedFileName(clean);
  }, [slide.subtitle]);

  const showCaptionOverlay = hasCustomTitle || hasCustomSubtitle;

  return (
    <div className="relative flex-1 w-full h-full p-0 m-0 border-none rounded-none flex items-center justify-center overflow-hidden bg-slate-950 select-none animate-fadeIn">
      {/* ─────────────────────────────────────────────────────────────
          1. SEAMLESS AMBIENT PROJECTION (FOR 'contain' or dark backdrop)
         ───────────────────────────────────────────────────────────── */}
      {fitMode === 'contain' && !isVideo && (
        <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
          <div
            className="absolute -inset-10 bg-center bg-cover filter blur-3xl scale-125 opacity-35"
            style={{ backgroundImage: `url(${slide.imageUrl})` }}
          />
          <div className="absolute inset-0 bg-slate-950/60 backdrop-blur-xs" />
        </div>
      )}

      {/* ─────────────────────────────────────────────────────────────
          2. FULL-BLEED EDGE-TO-EDGE MEDIA CONTAINER
             w-full h-full p-0 m-0 border-none rounded-none
         ───────────────────────────────────────────────────────────── */}
      <div className="relative w-full h-full p-0 m-0 border-none rounded-none flex items-center justify-center overflow-hidden z-10">
        {isVideo ? (
          <video
            src={slide.imageUrl}
            autoPlay
            loop
            muted
            playsInline
            className={`w-full h-full p-0 m-0 border-none rounded-none ${
              fitMode === 'contain' ? 'object-contain' : 'object-cover'
            }`}
          />
        ) : (
          <img
            src={slide.imageUrl}
            alt={hasCustomTitle ? slide.title : 'Workshop Advertisement'}
            className={`w-full h-full p-0 m-0 border-none rounded-none ${
              fitMode === 'contain' ? 'object-contain' : 'object-cover'
            } transition-transform duration-700`}
          />
        )}
      </div>

      {/* ─────────────────────────────────────────────────────────────
          3. CLEAN COMPANY LOGO OVERLAY IN TOP CORNER
         ───────────────────────────────────────────────────────────── */}
      <div className="absolute top-4 left-4 sm:top-6 sm:left-6 z-30 flex items-center gap-3 pointer-events-none">
        <div className="flex items-center gap-3 px-3.5 py-2 rounded-2xl bg-slate-950/80 border border-slate-700/60 shadow-2xl backdrop-blur-md">
          <img
            src={companyLogoUrl}
            alt={companyName}
            className="h-8 sm:h-10 w-auto object-contain filter drop-shadow max-w-[130px] sm:max-w-[170px]"
          />
          <div className="hidden sm:block border-l border-slate-700/80 pl-3 text-left">
            <span className="text-xs font-black text-white tracking-wider block uppercase">
              {companyName}
            </span>
            <span className="text-[10px] text-amber-400 font-bold uppercase tracking-widest block">
              Workshop TV Broadcast
            </span>
          </div>
        </div>

        <div className="hidden md:flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-amber-500/15 border border-amber-500/30 text-amber-400 text-xs font-bold shadow-lg backdrop-blur-md">
          <Megaphone className="w-3.5 h-3.5 animate-pulse" />
          <span>Featured Ad</span>
        </div>
      </div>

      {/* ─────────────────────────────────────────────────────────────
          4. TOP-RIGHT COUNTDOWN TICKER & SKIP BUTTON OVERLAY
         ───────────────────────────────────────────────────────────── */}
      <div className="absolute top-4 right-4 sm:top-6 sm:right-6 z-30 flex items-center gap-2.5">
        <div className="flex items-center gap-2 px-3.5 py-2 rounded-2xl bg-slate-950/80 border border-slate-700/60 text-xs font-mono font-bold text-slate-200 shadow-2xl backdrop-blur-md">
          <Clock className="w-3.5 h-3.5 text-amber-400" />
          <span>
            NEXT IN <strong className="text-amber-400">{secondsRemaining}s</strong>
          </span>
          <span className="text-slate-600">|</span>
          <span className="text-slate-400">
            SLIDE {slideIndex + 1}/{totalSlides}
          </span>
        </div>

        {onSkipToSchedule && (
          <button
            type="button"
            onClick={onSkipToSchedule}
            className="px-3.5 py-2 text-xs font-bold text-slate-300 hover:text-white bg-slate-900/80 hover:bg-slate-800 border border-slate-700 hover:border-slate-500 rounded-2xl transition cursor-pointer shadow-xl backdrop-blur-md"
            title="Return immediately to Workshop Schedule table"
          >
            Skip to Schedule
          </button>
        )}
      </div>

      {/* ─────────────────────────────────────────────────────────────
          5. OPTIONAL EXPLICIT CUSTOM CAPTION OVERLAY
             (Completely hidden if no custom title/subtitle is set)
         ───────────────────────────────────────────────────────────── */}
      {showCaptionOverlay && (
        <div className="absolute bottom-8 inset-x-0 z-30 flex justify-center pointer-events-none px-6">
          <div className="bg-slate-950/85 backdrop-blur-md border border-slate-700/70 rounded-2xl py-3 px-6 text-center max-w-3xl shadow-2xl">
            {hasCustomTitle && (
              <h2 className="text-lg sm:text-xl md:text-2xl font-black text-white tracking-wide drop-shadow-md">
                {slide.title}
              </h2>
            )}
            {hasCustomSubtitle && (
              <p className="text-xs sm:text-sm font-semibold text-slate-300 drop-shadow mt-0.5">
                {slide.subtitle}
              </p>
            )}
          </div>
        </div>
      )}

      {/* ─────────────────────────────────────────────────────────────
          6. CAROUSEL DOTS & COUNTDOWN PROGRESS BAR
         ───────────────────────────────────────────────────────────── */}
      <div className="absolute bottom-3 right-6 z-30 flex items-center gap-1.5 bg-slate-950/75 backdrop-blur-md px-3 py-1.5 rounded-full border border-slate-800 shadow-xl">
        {Array.from({ length: totalSlides }).map((_, idx) => (
          <div
            key={idx}
            className={`h-2 rounded-full transition-all duration-300 ${
              idx === slideIndex
                ? 'w-7 bg-amber-400 shadow-md shadow-amber-400/50'
                : 'w-2 bg-slate-700'
            }`}
          />
        ))}
      </div>

      {/* Full-Width Real-time Countdown Progress Bar at Very Edge */}
      <div className="absolute bottom-0 inset-x-0 z-30 w-full bg-slate-900/60 h-1.5 backdrop-blur-xs">
        <div
          className="h-full bg-gradient-to-r from-amber-500 via-orange-500 to-amber-400 transition-all duration-100 ease-linear shadow-md"
          style={{ width: `${progressPercent}%` }}
        />
      </div>
    </div>
  );
};

export default TvPromoSlideView;
