// src/components/vehicles/VehicleUndoSaleModal.tsx

import React, { useState } from 'react';
import { doc, updateDoc } from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { Vehicle } from '../../types';
import { createFinanceTransaction } from '../../utils/financeTransactions'; 
import toast from 'react-hot-toast';
import Modal from '../ui/Modal';

interface VehicleUndoSaleModalProps {
  vehicle: Vehicle | null;
  onClose: () => void;
}

const VehicleUndoSaleModal: React.FC<VehicleUndoSaleModalProps> = ({ vehicle, onClose }) => {
  const [loading, setLoading] = useState(false);

  if (!vehicle) return null;

  const handleUndo = async () => {
    setLoading(true);

    try {
      // 1. Create a Reversal Transaction (Expense) if there was a sale price
      if (vehicle.salePrice && vehicle.salePrice > 0) {
        
        const vehicleOwner = vehicle.owner
        ? {
            name: vehicle.owner.name,
            isDefault: vehicle.owner.isDefault ?? false,
          }
        : undefined;

        await createFinanceTransaction({
          type: 'expense', // Opposite of the 'income' generated by the sale
          category: 'vehicle-sale-reversal',
          amount: vehicle.salePrice,
          description: `Correction: Undo sale of vehicle ${vehicle.make} ${vehicle.model} (${vehicle.registrationNumber})`,
          referenceId: vehicle.id,
          vehicleId: vehicle.id,
          vehicleName: `${vehicle.make} ${vehicle.model} (${vehicle.registrationNumber})`,
          vehicleOwner,
          paymentStatus: 'paid',
          date: new Date(),
          accountFrom: vehicle.owner?.accountId || undefined,
          groupId: vehicle.assignedGroupId || undefined, 
          departmentId: vehicle.assignedDepartmentId || undefined, // ✅ Pass the vehicle's assigned department for the reversal
          departmentName: vehicle.assignedDepartmentName || undefined, // ✅ Pass the vehicle's assigned department name
        });
      }

      // 2. Update vehicle record to remove sold status
      await updateDoc(doc(db, 'vehicles', vehicle.id), {
        status: 'active',
        soldDate: null,
        salePrice: null,
        updatedAt: new Date()
      });

      toast.success('Vehicle sale status undone & finance reversed');
      onClose();
    } catch (error) {
      console.error('Error undoing vehicle sale:', error);
      toast.error('Failed to undo vehicle sale status');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Modal
      isOpen={!!vehicle}
      onClose={onClose}
      title="Undo Vehicle Sale"
      theme="navy"
      size="md"
    >
      <div className="space-y-5">
        <div className="bg-amber-950/40 border border-amber-500/40 rounded-2xl p-5 text-amber-200 shadow-inner">
          <p className="text-sm font-medium">
            This will revert the vehicle status to <strong className="text-white font-bold">Active</strong>.
          </p>
          {vehicle.salePrice && vehicle.salePrice > 0 && (
            <p className="text-sm text-amber-300/90 mt-2">
              A reversal transaction (Expense) of <strong className="text-white font-bold">£{vehicle.salePrice.toLocaleString()}</strong> will be automatically created to reverse the original sale income.
            </p>
          )}
        </div>

        <p className="text-sm text-slate-300">
          Are you sure you want to proceed with reversing the sold status for <strong className="text-white">{vehicle.registrationNumber}</strong>?
        </p>

        <div className="flex justify-end space-x-3 pt-2">
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2.5 text-sm font-semibold text-slate-300 bg-[#0F111A] border border-[#2B314E] rounded-xl hover:bg-[#1C2038] hover:text-white transition-all cursor-pointer"
          >
            Cancel
          </button>
          <button
            onClick={handleUndo}
            disabled={loading}
            className="px-5 py-2.5 text-sm font-bold text-white bg-orange-600 hover:bg-orange-500 rounded-xl shadow-md disabled:opacity-50 transition-all cursor-pointer"
          >
            {loading ? 'Processing...' : 'Undo Sold Status'}
          </button>
        </div>
      </div>
    </Modal>
  );
};

export default VehicleUndoSaleModal;