// src/components/vehicles/VehicleUndoSaleModal.tsx

import React, { useState } from 'react';
import { doc, updateDoc } from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { Vehicle } from '../../types';
import { createFinanceTransaction } from '../../utils/financeTransactions'; // Import transaction helper
import toast from 'react-hot-toast';
import Modal from '../ui/Modal';

interface VehicleUndoSaleModalProps {
  vehicle: Vehicle | null;
  onClose: () => void;
}

const VehicleUndoSaleModal: React.FC<VehicleUndoSaleModalProps> = ({ vehicle, onClose }) => {
  const [loading, setLoading] = useState(false);

  if (!vehicle) return null;

  const handleUndo = async () => {
    setLoading(true);

    try {
      // 1. Create a Reversal Transaction (Expense) if there was a sale price
      if (vehicle.salePrice && vehicle.salePrice > 0) {
        
        const vehicleOwner = vehicle.owner
        ? {
            name: vehicle.owner.name,
            isDefault: vehicle.owner.isDefault ?? false,
          }
        : undefined;

        await createFinanceTransaction({
          type: 'expense', // Opposite of the 'income' generated by the sale
          category: 'vehicle-sale-reversal',
          amount: vehicle.salePrice,
          description: `Correction: Undo sale of vehicle ${vehicle.make} ${vehicle.model} (${vehicle.registrationNumber})`,
          referenceId: vehicle.id,
          vehicleId: vehicle.id,
          vehicleName: `${vehicle.make} ${vehicle.model} (${vehicle.registrationNumber})`,
          vehicleOwner,
          paymentStatus: 'paid',
          date: new Date(),
          // ✅ NEW: If vehicle has a linked account, debit it (accountFrom) to reverse the income
          accountFrom: vehicle.owner?.accountId || undefined,
        });
      }

      // 2. Update vehicle record to remove sold status
      await updateDoc(doc(db, 'vehicles', vehicle.id), {
        status: 'active',
        soldDate: null,
        salePrice: null,
        updatedAt: new Date()
      });

      toast.success('Vehicle sale status undone & finance reversed');
      onClose();
    } catch (error) {
      console.error('Error undoing vehicle sale:', error);
      toast.error('Failed to undo vehicle sale status');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Modal
      isOpen={!!vehicle}
      onClose={onClose}
      title="Undo Vehicle Sale"
    >
      <div className="space-y-4">
        <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4">
          <div className="flex">
            <div className="ml-3">
              <p className="text-sm text-yellow-700">
                This will revert the vehicle status to <strong>Active</strong>.
              </p>
              {vehicle.salePrice && vehicle.salePrice > 0 && (
                 <p className="text-sm text-yellow-700 mt-2">
                   A negative transaction (Expense) of <strong>£{vehicle.salePrice.toLocaleString()}</strong> will be created to reverse the original sale income.
                 </p>
              )}
            </div>
          </div>
        </div>

        <p className="text-sm text-gray-500">
          Are you sure you want to proceed?
        </p>

        <div className="flex justify-end space-x-3">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            onClick={handleUndo}
            disabled={loading}
            className="px-4 py-2 text-sm font-medium text-white bg-orange-600 border border-transparent rounded-md hover:bg-orange-700"
          >
            {loading ? 'Processing...' : 'Undo Sold Status'}
          </button>
        </div>
      </div>
    </Modal>
  );
};

export default VehicleUndoSaleModal;